version: '3.8'
services:
    apache:
        image: php:7.2-apache
        ports:
         - 80:80
        volumes: &appvolumes
         - "./html:/var/www/html:delegated"
         - "./nginx_conf/:/etc/nginx/conf.d:delegated"
    cli:
        image: php:7.2-cli
        command: bash -c "tail -f /dev/null"
        volumes: *appvolumes
    mysql:
        image: mysql:5.7
        environment: 
         - MYSQL_ROOT_PASSWORD=magento
         - MYSQL_DATABASE=magento
         - MYSQL_USER=magento
         - MYSQL_PASSWORD=magento
        links: 
         - apache
        ports:
         - "3306:3306"
        # volumes:
        #  - ./mysql:/var/lib/mysql