FROM node:lts-alpine
RUN npm install -g http-server @vue/cli @vue/cli-init
#RUN yarn global add @vue/cli-init
WORKDIR /app
EXPOSE 80
CMD [ "npm run serve", "dist" ]

## docker run -it -d -p 80:8081 --name vuecli grayson/vuecli 
## docker exec -it vuecli sh
# vue create .
# npm run serve